-- quantity can now be 0: a bottle that's in the database but not on hand. The Cellar list shows only
-- quantity > 0; everything (on hand or not) feeds the Add-a-Bottle type-ahead. Finishing the last bottle
-- sets it to 0 instead of deleting it, so it's quick to add again.
-- SQLite can't change a CHECK constraint in place, so rebuild the table with the same columns.
CREATE TABLE bottles_new (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL CHECK (category IN ('whiskey','wine','beer')),
  name TEXT NOT NULL,
  maker TEXT,
  notes TEXT,
  abv REAL,
  photo_url TEXT,
  added_at TEXT DEFAULT CURRENT_TIMESTAMP,
  purchased_on TEXT,
  vintage INTEGER,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 0)
);
INSERT INTO bottles_new (id, category, name, maker, notes, abv, photo_url, added_at, purchased_on, vintage, quantity)
  SELECT id, category, name, maker, notes, abv, photo_url, added_at, purchased_on, vintage, quantity FROM bottles;
DROP TABLE bottles;
ALTER TABLE bottles_new RENAME TO bottles;

-- Starter catalog of common bottles (quantity 0) for the type-ahead. ABVs are the standard US bottling;
-- wine ABV is left blank because it changes by vintage. Skips anything already in the table by name.
WITH catalog(category, name, maker, abv) AS (VALUES
  -- Bourbon
  ('whiskey', 'Eagle Rare 10 Year', 'Buffalo Trace Distillery', 45),
  ('whiskey', 'Blanton''s Original Single Barrel', 'Buffalo Trace Distillery', 46.5),
  ('whiskey', 'Weller Antique 107', 'Buffalo Trace Distillery', 53.5),
  ('whiskey', 'Maker''s Mark', 'Maker''s Mark Distillery', 45),
  ('whiskey', 'Maker''s Mark 46', 'Maker''s Mark Distillery', 47),
  ('whiskey', 'Woodford Reserve', 'Woodford Reserve Distillery', 45.2),
  ('whiskey', 'Woodford Reserve Double Oaked', 'Woodford Reserve Distillery', 45.2),
  ('whiskey', 'Knob Creek 9 Year', 'James B. Beam Distilling Co.', 50),
  ('whiskey', 'Jim Beam White Label', 'James B. Beam Distilling Co.', 40),
  ('whiskey', 'Basil Hayden', 'James B. Beam Distilling Co.', 40),
  ('whiskey', 'Old Grand-Dad 114', 'James B. Beam Distilling Co.', 57),
  ('whiskey', 'Bulleit Bourbon', 'Bulleit Distilling Co.', 45),
  ('whiskey', 'Four Roses Bourbon', 'Four Roses Distillery', 40),
  ('whiskey', 'Four Roses Small Batch', 'Four Roses Distillery', 45),
  ('whiskey', 'Four Roses Single Barrel', 'Four Roses Distillery', 50),
  ('whiskey', 'Wild Turkey 101', 'Wild Turkey Distillery', 50.5),
  ('whiskey', 'Russell''s Reserve 10 Year', 'Wild Turkey Distillery', 45),
  ('whiskey', 'Elijah Craig Small Batch', 'Heaven Hill Distillery', 47),
  ('whiskey', 'Larceny Small Batch', 'Heaven Hill Distillery', 46),
  ('whiskey', 'Evan Williams Black Label', 'Heaven Hill Distillery', 43),
  ('whiskey', 'Henry McKenna 10 Year Bottled in Bond', 'Heaven Hill Distillery', 50),
  ('whiskey', 'Old Forester 86 Proof', 'Old Forester Distilling Co.', 43),
  ('whiskey', 'Old Forester 1920 Prohibition Style', 'Old Forester Distilling Co.', 57.5),
  ('whiskey', 'Angel''s Envy', 'Angel''s Envy Distillery', 43.3),
  ('whiskey', 'Michter''s US*1 Small Batch Bourbon', 'Michter''s Distillery', 45.7),
  ('whiskey', '1792 Small Batch', 'Barton 1792 Distillery', 46.85),
  ('whiskey', 'Jefferson''s Very Small Batch', 'Jefferson''s Bourbon', 41.15),
  -- Rye
  ('whiskey', 'Rittenhouse Rye Bottled in Bond', 'Heaven Hill Distillery', 50),
  ('whiskey', 'Sazerac Rye', 'Buffalo Trace Distillery', 45),
  ('whiskey', 'Bulleit Rye', 'Bulleit Distilling Co.', 45),
  ('whiskey', 'WhistlePig 10 Year Rye', 'WhistlePig', 50),
  ('whiskey', 'High West Double Rye', 'High West Distillery', 46),
  ('whiskey', 'Michter''s US*1 Rye', 'Michter''s Distillery', 42.4),
  ('whiskey', 'Old Forester Rye', 'Old Forester Distilling Co.', 50),
  ('whiskey', 'Woodford Reserve Rye', 'Woodford Reserve Distillery', 45.2),
  ('whiskey', 'Knob Creek Rye', 'James B. Beam Distilling Co.', 50),
  -- Tennessee & Canadian
  ('whiskey', 'Jack Daniel''s Old No. 7', 'Jack Daniel Distillery', 40),
  ('whiskey', 'Gentleman Jack', 'Jack Daniel Distillery', 40),
  ('whiskey', 'Jack Daniel''s Single Barrel Select', 'Jack Daniel Distillery', 47),
  ('whiskey', 'George Dickel No. 12', 'Cascade Hollow Distilling Co.', 45),
  ('whiskey', 'Crown Royal', 'Crown Royal', 40),
  ('whiskey', 'Crown Royal Northern Harvest Rye', 'Crown Royal', 45),
  -- Scotch
  ('whiskey', 'The Glenlivet 12 Year', 'The Glenlivet', 40),
  ('whiskey', 'Glenfiddich 12 Year', 'Glenfiddich', 40),
  ('whiskey', 'The Macallan 12 Year Double Cask', 'The Macallan', 43),
  ('whiskey', 'Lagavulin 16 Year', 'Lagavulin', 43),
  ('whiskey', 'Laphroaig 10 Year', 'Laphroaig', 43),
  ('whiskey', 'Ardbeg 10 Year', 'Ardbeg', 46),
  ('whiskey', 'Talisker 10 Year', 'Talisker', 45.8),
  ('whiskey', 'Oban 14 Year', 'Oban', 43),
  ('whiskey', 'The Balvenie DoubleWood 12 Year', 'The Balvenie', 43),
  ('whiskey', 'Highland Park 12 Year', 'Highland Park', 43),
  ('whiskey', 'Glenmorangie The Original 10 Year', 'Glenmorangie', 40),
  ('whiskey', 'The Dalmore 12 Year', 'The Dalmore', 40),
  ('whiskey', 'Johnnie Walker Black Label', 'Johnnie Walker', 40),
  ('whiskey', 'Johnnie Walker Blue Label', 'Johnnie Walker', 40),
  ('whiskey', 'Monkey Shoulder', 'William Grant & Sons', 43),
  -- Irish
  ('whiskey', 'Jameson', 'Irish Distillers', 40),
  ('whiskey', 'Redbreast 12 Year', 'Irish Distillers', 40),
  ('whiskey', 'Green Spot', 'Irish Distillers', 40),
  ('whiskey', 'Tullamore D.E.W.', 'Tullamore Distillery', 40),
  ('whiskey', 'Bushmills Original', 'Bushmills Distillery', 40),
  -- Japanese
  ('whiskey', 'Suntory Toki', 'Suntory', 43),
  ('whiskey', 'Hibiki Japanese Harmony', 'Suntory', 43),
  ('whiskey', 'Yamazaki 12 Year', 'Suntory', 43),
  ('whiskey', 'Nikka From the Barrel', 'Nikka', 51.4),

  -- Red
  ('wine', 'Caymus Cabernet Sauvignon', 'Caymus Vineyards', NULL),
  ('wine', 'Bonanza Cabernet Sauvignon', 'Caymus Vineyards', NULL),
  ('wine', 'Silver Oak Alexander Valley Cabernet Sauvignon', 'Silver Oak Cellars', NULL),
  ('wine', 'Jordan Cabernet Sauvignon', 'Jordan Vineyard & Winery', NULL),
  ('wine', 'Stag''s Leap Wine Cellars Artemis Cabernet Sauvignon', 'Stag''s Leap Wine Cellars', NULL),
  ('wine', 'DAOU Cabernet Sauvignon', 'DAOU Vineyards', NULL),
  ('wine', 'Josh Cellars Cabernet Sauvignon', 'Josh Cellars', NULL),
  ('wine', 'Opus One', 'Opus One Winery', NULL),
  ('wine', 'Orin Swift 8 Years in the Desert', 'Orin Swift Cellars', NULL),
  ('wine', 'The Prisoner Red Blend', 'The Prisoner Wine Company', NULL),
  ('wine', 'Apothic Red', 'Apothic Wines', NULL),
  ('wine', '19 Crimes Red Blend', '19 Crimes', NULL),
  ('wine', 'Duckhorn Napa Valley Merlot', 'Duckhorn Vineyards', NULL),
  ('wine', 'Meiomi Pinot Noir', 'Meiomi', NULL),
  ('wine', 'Belle Glos Clark & Telephone Pinot Noir', 'Belle Glos', NULL),
  ('wine', 'La Crema Sonoma Coast Pinot Noir', 'La Crema', NULL),
  ('wine', 'Decoy Pinot Noir', 'Decoy Wines', NULL),
  ('wine', 'Erath Oregon Pinot Noir', 'Erath Winery', NULL),
  ('wine', 'Catena Malbec', 'Bodega Catena Zapata', NULL),
  ('wine', 'Penfolds Bin 389 Cabernet Shiraz', 'Penfolds', NULL),
  ('wine', 'Ruffino Riserva Ducale Chianti Classico', 'Ruffino', NULL),
  ('wine', 'Tignanello', 'Marchesi Antinori', NULL),
  -- White
  ('wine', 'Kendall-Jackson Vintner''s Reserve Chardonnay', 'Kendall-Jackson', NULL),
  ('wine', 'La Crema Sonoma Coast Chardonnay', 'La Crema', NULL),
  ('wine', 'Rombauer Chardonnay', 'Rombauer Vineyards', NULL),
  ('wine', 'Sonoma-Cutrer Russian River Ranches Chardonnay', 'Sonoma-Cutrer', NULL),
  ('wine', 'Cakebread Cellars Chardonnay', 'Cakebread Cellars', NULL),
  ('wine', 'Cloudy Bay Sauvignon Blanc', 'Cloudy Bay', NULL),
  ('wine', 'Kim Crawford Sauvignon Blanc', 'Kim Crawford', NULL),
  ('wine', 'Whitehaven Sauvignon Blanc', 'Whitehaven', NULL),
  ('wine', 'Santa Margherita Pinot Grigio', 'Santa Margherita', NULL),
  ('wine', 'Chateau Ste. Michelle Riesling', 'Chateau Ste. Michelle', NULL),
  -- Rosé & sparkling
  ('wine', 'Whispering Angel Rosé', 'Château d''Esclans', NULL),
  ('wine', 'Miraval Rosé', 'Château Miraval', NULL),
  ('wine', 'Veuve Clicquot Yellow Label Brut', 'Veuve Clicquot', NULL),
  ('wine', 'Moët & Chandon Impérial Brut', 'Moët & Chandon', NULL),
  ('wine', 'Dom Pérignon', 'Moët & Chandon', NULL),
  ('wine', 'Chandon Brut', 'Chandon', NULL),
  ('wine', 'La Marca Prosecco', 'La Marca', NULL),

  -- Craft & specialty
  ('beer', 'Blue Moon Belgian White', 'Blue Moon Brewing Company', 5.4),
  ('beer', 'Pliny the Elder', 'Russian River Brewing Company', 8),
  ('beer', 'Heady Topper', 'The Alchemist', 8),
  ('beer', 'Julius', 'Tree House Brewing Company', 6.8),
  ('beer', 'Sierra Nevada Pale Ale', 'Sierra Nevada Brewing Co.', 5.6),
  ('beer', 'Sierra Nevada Torpedo Extra IPA', 'Sierra Nevada Brewing Co.', 7.2),
  ('beer', 'Bell''s Two Hearted IPA', 'Bell''s Brewery', 7),
  ('beer', 'Bell''s Oberon', 'Bell''s Brewery', 5.8),
  ('beer', 'Founders All Day IPA', 'Founders Brewing Co.', 4.7),
  ('beer', 'Founders Breakfast Stout', 'Founders Brewing Co.', 8.3),
  ('beer', 'Founders KBS', 'Founders Brewing Co.', 12),
  ('beer', 'Goose Island IPA', 'Goose Island Beer Co.', 5.9),
  ('beer', 'Lagunitas IPA', 'Lagunitas Brewing Company', 6.2),
  ('beer', 'Dogfish Head 60 Minute IPA', 'Dogfish Head Craft Brewery', 6),
  ('beer', 'Dogfish Head 90 Minute IPA', 'Dogfish Head Craft Brewery', 9),
  ('beer', 'Stone IPA', 'Stone Brewing', 6.9),
  ('beer', 'Elysian Space Dust IPA', 'Elysian Brewing', 8.2),
  ('beer', 'Cigar City Jai Alai IPA', 'Cigar City Brewing', 7.5),
  ('beer', 'Voodoo Ranger IPA', 'New Belgium Brewing', 7),
  ('beer', 'Fat Tire Ale', 'New Belgium Brewing', 5.2),
  ('beer', 'Dale''s Pale Ale', 'Oskar Blues Brewery', 6.5),
  ('beer', 'Allagash White', 'Allagash Brewing Company', 5.2),
  ('beer', 'Great Lakes Edmund Fitzgerald Porter', 'Great Lakes Brewing Co.', 6),
  ('beer', 'Left Hand Milk Stout Nitro', 'Left Hand Brewing Company', 6),
  ('beer', 'Deschutes Black Butte Porter', 'Deschutes Brewery', 5.2),
  ('beer', 'Samuel Adams Boston Lager', 'Boston Beer Company', 5),
  ('beer', 'Leinenkugel''s Summer Shandy', 'Jacob Leinenkugel Brewing Company', 4.2),
  ('beer', 'Angry Orchard Crisp Apple', 'Angry Orchard', 5),
  -- Imports
  ('beer', 'Guinness Draught', 'Guinness', 4.2),
  ('beer', 'Weihenstephaner Hefeweissbier', 'Bayerische Staatsbrauerei Weihenstephan', 5.4),
  ('beer', 'Paulaner Hefe-Weizen', 'Paulaner Brauerei', 5.5),
  ('beer', 'Duvel', 'Duvel Moortgat', 8.5),
  ('beer', 'Chimay Grande Réserve (Blue)', 'Chimay', 9),
  ('beer', 'Delirium Tremens', 'Brouwerij Huyghe', 8.5),
  ('beer', 'Westmalle Tripel', 'Westmalle Abbey', 9.5),
  ('beer', 'Stella Artois', 'Stella Artois', 5),
  ('beer', 'Heineken', 'Heineken', 5),
  ('beer', 'Modelo Especial', 'Grupo Modelo', 4.4),
  ('beer', 'Corona Extra', 'Grupo Modelo', 4.6),
  -- Everyday
  ('beer', 'Yuengling Traditional Lager', 'D.G. Yuengling & Son', 4.5),
  ('beer', 'Michelob Ultra', 'Anheuser-Busch', 4.2),
  ('beer', 'Bud Light', 'Anheuser-Busch', 4.2),
  ('beer', 'Coors Light', 'Molson Coors', 4.2),
  ('beer', 'Miller Lite', 'Molson Coors', 4.2)
)
INSERT INTO bottles (category, name, maker, abv, quantity)
SELECT c.category, c.name, c.maker, c.abv, 0 FROM catalog c
WHERE NOT EXISTS (SELECT 1 FROM bottles b WHERE b.category = c.category AND lower(b.name) = lower(c.name));
